# Generated by Django 3.1.3 on 2021-09-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=50)),
                ('tournament', models.CharField(max_length=100)),
                ('start_time', models.IntegerField()),
                ('team_A', models.CharField(max_length=50)),
                ('team_B', models.CharField(max_length=50)),
                ('player1', models.CharField(max_length=50)),
                ('credit1', models.IntegerField()),
                ('player2', models.CharField(max_length=50)),
                ('credit2', models.IntegerField()),
                ('player3', models.CharField(max_length=50)),
                ('credit3', models.IntegerField()),
                ('player4', models.CharField(max_length=50)),
                ('credit4', models.IntegerField()),
                ('player5', models.CharField(max_length=50)),
                ('credit5', models.IntegerField()),
                ('player6', models.CharField(max_length=50)),
                ('credit6', models.IntegerField()),
                ('player7', models.CharField(max_length=50)),
                ('credit7', models.IntegerField()),
                ('player8', models.CharField(max_length=50)),
                ('credit8', models.IntegerField()),
                ('player9', models.CharField(max_length=50)),
                ('credit9', models.IntegerField()),
                ('player10', models.CharField(max_length=50)),
                ('credit10', models.IntegerField()),
            ],
        ),
    ]
