# Generated by Django 3.1.3 on 2021-09-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='entry1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='entry2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='entry3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='entry4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='prize1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='prize2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='prize3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='prize4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='credit9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
